In [1]:
import numpy as np

In [6]:
import tensorflow as tf

In [28]:
# a demo array (1, 4, 16) for input
demo_input = np.zeros([1, 4, 64])

In [29]:
# get the number of timesteps per row
T = tf.shape(demo_input)[1]
T

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [30]:
pos = tf.reshape(tf.range(0.0, T, dtype=tf.float32), [-1, 1])
pos

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [2.],
       [3.]], dtype=float32)>

In [31]:
repr_dim = tf.shape(demo_input)[-1]
repr_dim

<tf.Tensor: shape=(), dtype=int32, numpy=64>

In [32]:
i = np.arange(0, repr_dim, 2, np.float32)
i

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50.,
       52., 54., 56., 58., 60., 62.], dtype=float32)

In [33]:
denom = np.reshape(np.power(10000.0, i/repr_dim), [1, -1])
denom

array([[1.00000000e+00, 1.33352143e+00, 1.77827941e+00, 2.37137371e+00,
        3.16227766e+00, 4.21696503e+00, 5.62341325e+00, 7.49894209e+00,
        1.00000000e+01, 1.33352143e+01, 1.77827941e+01, 2.37137371e+01,
        3.16227766e+01, 4.21696503e+01, 5.62341325e+01, 7.49894209e+01,
        1.00000000e+02, 1.33352143e+02, 1.77827941e+02, 2.37137371e+02,
        3.16227766e+02, 4.21696503e+02, 5.62341325e+02, 7.49894209e+02,
        1.00000000e+03, 1.33352143e+03, 1.77827941e+03, 2.37137371e+03,
        3.16227766e+03, 4.21696503e+03, 5.62341325e+03, 7.49894209e+03]])

In [34]:
enc = tf.expand_dims(tf.concat([tf.sin(pos / denom), tf.cos(pos / denom)], 1), 0)
enc

<tf.Tensor: shape=(1, 4, 64), dtype=float32, numpy=
array([[[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          1.0000000e+00,  1.0000000e+00,  1.0000000e+00,  1.0000000e+00,
          1.0000000e+00,  1.0000000e+00,  1.0000000e+00,  1.0000000e+00,
          1.0000000e+00,  1.0000000e+00,  1.0000000e+00,  1.0000000e+00,
          1.0000000e+00,  1.0000000e+00,  1.0000000e+00,  1.0000000e+00,
          1.0000000e+00,  1.0000000e+00,  1.0000000e+00,  1.0000000e+00,

In [35]:
tf.tile(enc, [tf.shape(demo_input)[0], 1, 1])

<tf.Tensor: shape=(1, 4, 64), dtype=float32, numpy=
array([[[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
          1.0000000e+00,  1.0000000e+00,  1.0000000e+00,  1.0000000e+00,
          1.0000000e+00,  1.0000000e+00,  1.0000000e+00,  1.0000000e+00,
          1.0000000e+00,  1.0000000e+00,  1.0000000e+00,  1.0000000e+00,
          1.0000000e+00,  1.0000000e+00,  1.0000000e+00,  1.0000000e+00,
          1.0000000e+00,  1.0000000e+00,  1.0000000e+00,  1.0000000e+00,

In [ ]:
# https://github.com/huseinzol05/Stock-Prediction-Models/blob/master/deep-learning/16.attention-is-all-you-need.ipynb

In [24]:
def sinusoidal_position_encoding(inputs, mask, repr_dim):
    T = tf.shape(inputs)[1]
    pos = tf.reshape(tf.range(0.0, tf.to_float(T), dtype=tf.float32), [-1, 1])
    i = np.arange(0, repr_dim, 2, np.float32)
    denom = np.reshape(np.power(10000.0, i / repr_dim), [1, -1])
    enc = tf.expand_dims(tf.concat([tf.sin(pos / denom), tf.cos(pos / denom)], 1), 0)
    return tf.tile(enc, [tf.shape(inputs)[0], 1, 1]) * tf.expand_dims(tf.to_float(mask), -1)