In [ ]:
# from https://www.tensorflow.org/tutorials/text/transformer

In [1]:
import numpy as np

In [12]:
import tensorflow as tf

In [5]:
def get_angles(pos, i, d_model):
  angle_rates = 1 / np.power(10000, (2 * (i//2)) / np.float32(d_model))
  return pos * angle_rates

def positional_encoding(positions, d_model):
  angle_rads = get_angles(np.arange(positions)[:, np.newaxis],
                          np.arange(d_model)[np.newaxis, :],
                          d_model)
  
  # apply sin to even indices in the array; 2i
  angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])
  
  # apply cos to odd indices in the array; 2i+1
  angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])
    
  pos_encoding = angle_rads[np.newaxis, ...]
    
  return pos_encoding

In [10]:
pos_encoding = positional_encoding(positions=256, d_model=64)

In [14]:
pos_encoding

array([[[ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00, ...,
          1.00000000e+00,  0.00000000e+00,  1.00000000e+00],
        [ 8.41470985e-01,  5.40302306e-01,  6.81561350e-01, ...,
          9.99999984e-01,  1.33352143e-04,  9.99999991e-01],
        [ 9.09297427e-01, -4.16146837e-01,  9.97479998e-01, ...,
          9.99999937e-01,  2.66704283e-04,  9.99999964e-01],
        ...,
        [ 9.94823729e-01, -1.01615692e-01,  9.41709403e-01, ...,
          9.98988100e-01,  3.37316922e-02,  9.99430925e-01],
        [ 4.51998898e-01, -8.92018495e-01,  9.18402109e-01, ...,
          9.98980086e-01,  3.38649681e-02,  9.99426417e-01],
        [-5.06391635e-01, -8.62303608e-01,  4.02392244e-01, ...,
          9.98972041e-01,  3.39982435e-02,  9.99421893e-01]]])

In [13]:
tf.squeeze(pos_encoding)

<tf.Tensor: shape=(256, 64), dtype=float64, numpy=
array([[ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00, ...,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00],
       [ 8.41470985e-01,  5.40302306e-01,  6.81561350e-01, ...,
         9.99999984e-01,  1.33352143e-04,  9.99999991e-01],
       [ 9.09297427e-01, -4.16146837e-01,  9.97479998e-01, ...,
         9.99999937e-01,  2.66704283e-04,  9.99999964e-01],
       ...,
       [ 9.94823729e-01, -1.01615692e-01,  9.41709403e-01, ...,
         9.98988100e-01,  3.37316922e-02,  9.99430925e-01],
       [ 4.51998898e-01, -8.92018495e-01,  9.18402109e-01, ...,
         9.98980086e-01,  3.38649681e-02,  9.99426417e-01],
       [-5.06391635e-01, -8.62303608e-01,  4.02392244e-01, ...,
         9.98972041e-01,  3.39982435e-02,  9.99421893e-01]])>